packages:
  - packages/*/*
  - apps/*

allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': false
  electron: true
  esbuild: true
  koffi: true
  node-addon-require-builtin: false
  node-pty: true
  protobufjs: false

patchedDependencies:
  '@deepseek-ai/dsh-client-ui-layout@0.1.0-rc.8': patches/@deepseek-ai__dsh-client-ui-layout@0.1.0-rc.8.patch
