packages:
  - packages/*/*
  - apps/*

allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': false
  electron: true
  esbuild: true
  koffi: true
  node-addon-require-builtin: false
  node-pty: true
  protobufjs: false

minimumReleaseAgeExclude:
  - '@deepseek-ai/dsh'
  - '@deepseek-ai/dsh-*'
  - '@xmldom/xmldom@0.9.12'

patchedDependencies:
  '@deepseek-ai/dsh-client-ui-agent-preset@0.1.1-rc.2': patches/@deepseek-ai__dsh-client-ui-agent-preset@0.1.1-rc.2.patch
  '@deepseek-ai/dsh-client-ui-conversation@0.1.1-rc.2': patches/@deepseek-ai__dsh-client-ui-conversation@0.1.1-rc.2.patch
  '@deepseek-ai/dsh-client-ui-layout@0.1.1-rc.2': patches/@deepseek-ai__dsh-client-ui-layout@0.1.1-rc.2.patch
  '@deepseek-ai/dsh-client-ui-primitives@0.1.1-rc.2': patches/@deepseek-ai__dsh-client-ui-primitives@0.1.1-rc.2.patch
