packages:
  - "packages/*"

allowBuilds:
  "@biomejs/biome": true
  electron: true
  electron-winstaller: false
  esbuild: true
  node-pty: true

onlyBuiltDependencies:
  - "@biomejs/biome"
  - electron
  - esbuild
  - node-pty
